version: "2.4"

services:
  php:
    build:
      context: ./
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.6.16
    ports:
      - "${DB_PORT}:3306"
    environment:
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
      MARIADB_DATABASE: "${DB_NAME}"
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
